#!/usr/bin/env python
"""Reference numbers for EVA's shared-with-MNE processing steps.

EVA and MNE-Python both implement bad-channel interpolation (Perrin spherical
splines), average referencing, epoch extraction, baseline correction, and
trial averaging. This generates a small, committed, synthetic fixture with
MNE's answers so a Swift test can feed the *same* inputs to EVA's own
functions and diff the outputs — the same fixture-pair pattern as
Tools/forward-compare (see its README).

    /Users/molfesepj/micromamba/envs/mne/bin/python Tools/mne-compare/make_reference.py

Writes EVATests/Fixtures/Compare/mne_reference.json.

## Electrode positions

Uses the same unit-sphere 10-05 coordinates EVA embeds in
EVACore/Channels/StandardMontageData.swift (generated by
Tools/resolve-validate/export_montages.py from MNE's bundled
`eeg_positions` TSVs) — both sides load literally the same numbers, so any
mismatch in the interpolation weights is EVA's spline math, not a coordinate
disagreement.

## Epoch-length convention (documented, not "fixed")

MNE's `Epochs(tmin, tmax)` includes both endpoints:
`n_times = round((tmax - tmin) * sfreq) + 1`. EVA's
`EpochingViewModel.makeBuildJob` computes
`epochLength = round((preStimulus + postStimulus) * sfreq)` — one sample
short of MNE's convention for the same tmin=-preStimulus/tmax=postStimulus.
The fixture records both counts so the Swift test asserts the *documented*
relationship (`mne_n_times == eva_epoch_length + 1`) rather than silently
comparing arrays of different length.

## Baseline-then-average vs average-then-baseline

MNE baseline-corrects each epoch before averaging (`Epochs(..., baseline=...)`
then `.average()`). EVA's PSA path averages raw epochs first and
baseline-corrects the *average* (`PSABuildResult.postProcessed`, called after
`.average()`). Both are linear mean operations over the same fixed window in
every trial, so they commute: `mean_i(x_i - mean(pre_i)) == mean_i(x_i) -
mean(mean_i(pre_i))`. The fixture includes both the per-trial-baselined
evoked (MNE's order) and the average-then-baseline evoked (EVA's order),
computed independently in numpy, so the Swift test can confirm EVA's answer
matches MNE's `Evoked.data` even though the intermediate steps differ in
order.
"""
import json
import os
import numpy as np
import mne

mne.set_log_level("WARNING")

ROOT = os.path.join(os.path.dirname(__file__), "..", "..")
OUT_DIR = os.path.join(ROOT, "EVATests", "Fixtures", "Compare")
OUT_PATH = os.path.join(OUT_DIR, "mne_reference.json")

MONTAGE_TSV = os.path.join(
    os.path.dirname(mne.__file__), "channels", "data", "montages", "spherical_1005.tsv"
)

CHANNELS = ["Fp1", "Fp2", "F3", "F4", "C3", "Cz", "C4", "P3", "P4", "O1", "O2", "T7"]
TARGET = "Cz"          # channel to mark bad and interpolate
REF_EXCLUDED = "T7"    # a separate channel excluded from the average reference
ALPHA = 1e-5           # regularization; matches EVA's SphericalSpline default lambda


def load_positions():
    positions = {}
    with open(MONTAGE_TSV) as f:
        f.readline()
        for line in f:
            label, x, y, z = line.split()
            if label in CHANNELS:
                positions[label] = np.array([float(x), float(y), float(z)])
    missing = [c for c in CHANNELS if c not in positions]
    assert not missing, f"missing positions for {missing}"
    return positions


def make_synthetic_data(sfreq, n_samples, rng):
    """Deterministic-but-nontrivial per-channel signal: a slow sine plus
    channel-specific noise, so interpolation/reference/baseline all do
    something a constant or a ramp would hide (e.g. a shared linear trend
    cancels in re-referencing whether or not it's implemented correctly)."""
    t = np.arange(n_samples) / sfreq
    data = np.zeros((len(CHANNELS), n_samples))
    for i, ch in enumerate(CHANNELS):
        phase = i * 0.7
        freq = 1.5 + 0.3 * i
        data[i] = (
            10 * np.sin(2 * np.pi * freq * t + phase)
            + 3 * rng.standard_normal(n_samples)
            + 0.5 * i  # per-channel DC offset
        )
    return data


def main():
    os.makedirs(OUT_DIR, exist_ok=True)
    positions = load_positions()
    rng = np.random.default_rng(20260918)

    sfreq = 250.0
    duration_s = 4.0
    n_samples = int(duration_s * sfreq)
    data_uv = make_synthetic_data(sfreq, n_samples, rng)  # microvolts, for readability
    data_v = data_uv * 1e-6

    info = mne.create_info(CHANNELS, sfreq, ch_types="eeg")
    raw = mne.io.RawArray(data_v.copy(), info, verbose=False)
    montage = mne.channels.make_dig_montage(
        ch_pos={ch: positions[ch] for ch in CHANNELS}, coord_frame="head"
    )
    raw.set_montage(montage)

    # ---------------------------------------------------------------- interpolation
    # Computed directly from MNE's own weight-matrix builder rather than via
    # `Raw.interpolate_bads()` — that path also fits a headshape sphere for its
    # sanity checks, which is irrelevant here (these are idealized unit-sphere
    # positions, not a digitized head) and produces spurious NaNs. The weight
    # matrix (`_make_interpolation_matrix`) is the actual Perrin-spline
    # implementation EVA's `SphericalSpline` is being measured against.
    good_labels = [c for c in CHANNELS if c != TARGET]
    pos_from = np.array([positions[c] for c in good_labels])
    pos_to = np.array([positions[TARGET]])
    from mne.channels.interpolation import _make_interpolation_matrix
    # `pinv`'s SVD hits a couple of near-zero singular values for this
    # electrode layout (a symmetric idealized montage, not a jittered real
    # digitization) and warns about it; the resulting weights are finite and
    # sum to 1, so this is scipy being chatty, not a real problem.
    with np.errstate(divide="ignore", over="ignore", invalid="ignore"):
        weight_row = _make_interpolation_matrix(pos_from, pos_to, alpha=ALPHA)[0]
    assert np.isfinite(weight_row).all() and abs(weight_row.sum() - 1) < 1e-6
    good_idx_interp = [CHANNELS.index(c) for c in good_labels]
    interpolated_uv = weight_row @ data_uv[good_idx_interp]

    # ---------------------------------------------------------------- average reference
    raw_ref = raw.copy()
    raw_ref.info["bads"] = [REF_EXCLUDED]
    raw_ref.set_eeg_reference(ref_channels="average", projection=False, verbose=False)
    # MNE's "average" reference with bads set still includes bads in the mean
    # unless picks excludes them explicitly; EVA always excludes the passed-in
    # bad set. Reproduce EVA's semantics by hand as the actual reference value
    # (this is what the Swift side is compared against, not raw MNE defaults —
    # see README for the picks= caveat).
    excluded_idx = CHANNELS.index(REF_EXCLUDED)
    good_idx = [i for i in range(len(CHANNELS)) if i != excluded_idx]
    ref_signal = data_uv[good_idx].mean(axis=0)
    avg_ref_uv = data_uv.copy()
    for i in range(len(CHANNELS)):
        avg_ref_uv[i] = data_uv[i] - ref_signal

    # ---------------------------------------------------------------- epoching / baseline / averaging
    pre_stimulus = 0.2
    post_stimulus = 0.8
    event_samples = [300, 500, 700]  # 3 trials, well inside the 1000-sample recording
    events = np.array([[s, 0, 1] for s in event_samples])

    eva_pre_samples = int(round(pre_stimulus * sfreq))
    eva_epoch_length = int(round((pre_stimulus + post_stimulus) * sfreq))

    epochs_raw = mne.Epochs(
        raw, events, event_id={"stim": 1}, tmin=-pre_stimulus, tmax=post_stimulus,
        baseline=None, preload=True, verbose=False,
    )
    mne_n_times = epochs_raw.get_data().shape[-1]

    # MNE's baseline=(None, 0) is CLOSED at both ends: it includes the sample
    # at t=0 (the event/stimulus sample itself) in the mean it subtracts. EVA's
    # `withBaselineCorrection` uses `preStart..<preEnd` — the pre-stimulus
    # window only, excluding the stimulus sample. That's a second, independent
    # convention difference from the epoch-length one above, and it's exact:
    # both fixtures below are computed, so the Swift test can show which one
    # EVA actually matches.
    epochs_baselined_inclusive = mne.Epochs(
        raw, events, event_id={"stim": 1}, tmin=-pre_stimulus, tmax=post_stimulus,
        baseline=(None, 0), preload=True, verbose=False,
    )
    evoked_mne_inclusive = epochs_baselined_inclusive.average().data * 1e6

    epochs_baselined_exclusive = mne.Epochs(
        raw, events, event_id={"stim": 1}, tmin=-pre_stimulus, tmax=post_stimulus,
        baseline=(None, -1.0 / sfreq), preload=True, verbose=False,
    )
    evoked_mne_exclusive = epochs_baselined_exclusive.average().data * 1e6  # baseline-per-trial, then average

    # EVA's order: average raw (unbaselined) trials first, then baseline-correct
    # the average over the same pre-stimulus window. Computed independently in
    # numpy (not by calling MNE's baseline code) so this is a real cross-check,
    # not a restatement of the same call.
    raw_trials_uv = epochs_raw.get_data() * 1e6  # (n_trials, n_channels, eva-convention length is n-1 short; see below)
    # Trim to EVA's own (shorter-by-one) window before doing EVA's own average,
    # since that's the array length EVA would actually build.
    eva_trials_uv = raw_trials_uv[:, :, :eva_epoch_length]
    eva_average_uv = eva_trials_uv.mean(axis=0)
    eva_pre_mean = eva_average_uv[:, :eva_pre_samples].mean(axis=1, keepdims=True)
    evoked_eva_order = eva_average_uv - eva_pre_mean

    # Direct sample-window check: EVA's per-trial extraction is
    # signal[event_sample - pre_samples : event_sample - pre_samples + epoch_length].
    # Confirm that window, read straight out of the continuous signal, matches
    # MNE's own per-trial data over the overlapping length.
    first_event = event_samples[0]
    eva_window_uv = data_uv[:, first_event - eva_pre_samples: first_event - eva_pre_samples + eva_epoch_length]

    def r(arr, ndigits=8):
        """Round to keep the committed fixture text small without giving up
        the precision a tight-tolerance comparison needs (8 decimal places on
        microvolt-scale numbers is ~1e-8 relative, far below any tolerance
        used in the Swift tests)."""
        return np.round(np.asarray(arr), ndigits).tolist()

    fixture = {
        "description": "Reference values for EVA-vs-MNE parity tests (see Tools/mne-compare).",
        "channels": CHANNELS,
        "positions": {c: positions[c].tolist() for c in CHANNELS},
        "sampling_rate": sfreq,
        "signal_uv": r(data_uv),
        "interpolation": {
            "target": TARGET,
            "good_channels": good_labels,
            "alpha": ALPHA,
            "weights": r(weight_row),
            "interpolated_uv": r(interpolated_uv),
        },
        "average_reference": {
            "excluded": REF_EXCLUDED,
            "output_uv": r(avg_ref_uv),
        },
        "epoching": {
            "pre_stimulus": pre_stimulus,
            "post_stimulus": post_stimulus,
            "event_samples": event_samples,
            "eva_pre_samples": eva_pre_samples,
            "eva_epoch_length": eva_epoch_length,
            "mne_n_times": mne_n_times,
            "first_event_window_uv": r(eva_window_uv),
            "evoked_mne_baseline_inclusive_uv": r(evoked_mne_inclusive[:, :eva_epoch_length]),
            "evoked_mne_baseline_exclusive_uv": r(evoked_mne_exclusive[:, :eva_epoch_length]),
            "evoked_eva_order_uv": r(evoked_eva_order),
        },
    }

    with open(OUT_PATH, "w") as f:
        json.dump(fixture, f, indent=1)
    print("wrote", OUT_PATH)
    print("interpolation weight sum:", weight_row.sum(), "(should be ~1)")
    print("mne_n_times - eva_epoch_length =", mne_n_times - eva_epoch_length, "(documented off-by-one)")
    print("max |evoked_mne_inclusive - evoked_eva_order| =",
          np.max(np.abs(evoked_mne_inclusive[:, :eva_epoch_length] - evoked_eva_order)),
          "(expected non-zero: inclusive vs exclusive baseline window)")
    print("max |evoked_mne_exclusive - evoked_eva_order| =",
          np.max(np.abs(evoked_mne_exclusive[:, :eva_epoch_length] - evoked_eva_order)),
          "(expected ~0: same window definition, order-of-operations equivalence)")


if __name__ == "__main__":
    main()
