//
//  ImpedanceModel.swift
//  EVA Simulate
//
//  Developed by P. Molfese, National Institutes of Health (NIH).
//
//  This software is a "work of the United States Government" prepared by a federal
//  employee as part of official duties. As such, it is not subject to copyright
//  protection within the United States (17 U.S.C. § 105). International copyrights
//  may apply.
//
//  Per-electrode impedance, written into the recording the way a real EGI system
//  records it, and tied to whatever is wrong with each channel.
//
//  EVA reads impedance from the `ICAL` calibration block in `info1.xml` and
//  feeds it into channel health scoring, where the default EGI-style bands are:
//  40 kΩ and under scores fully good, 40-60 good, 60-70 fair, 70-120 poor, and
//  120 and above scores zero. The values generated here are chosen against those
//  bands so a demo recording's health report says something meaningful.
//
//  The interesting part is the mapping from defect to impedance, because it is
//  deliberately *not* one-to-one:
//
//  * A high-impedance contact — the `noisy`, `drift`, `pop` and `line` defects —
//    reads high, and impedance correctly predicts the bad data.
//  * A **bridged or shorted** electrode — the `flat` defect — reads *low*, often
//    lower than a good channel, because the electrolyte path is too good. Its
//    data is unusable and its impedance is excellent.
//
//  That second case is the one worth teaching. Impedance is a useful screen, not
//  a proxy for data quality: it catches the electrode that is barely connected
//  and misses the two that are connected to each other. A student who has seen a
//  channel score 1.0 on impedance while being visibly flat will remember that.
//

import Foundation

nonisolated enum ImpedanceModel {

    private static let boltzmannJoulesPerKelvin = 1.380649e-23

    /// Plausible impedance, in kΩ, for a channel carrying `defect` (or nil for a
    /// healthy one). Ranges are stated against EVA's default health bands.
    static func range(for defect: ChannelDefect?) -> ClosedRange<Double> {
        switch defect {
        case .none:
            // Informational: healthy channels are actually generated by scatter
            // around `impedanceTypicalKOhm`, which the default of 12 puts here.
            return 4...30          // comfortably inside "great"
        case .flat:
            return 0.4...3         // bridged/shorted: scores great, data unusable
        case .noisy:
            return 110...220       // scores zero
        case .drift:
            return 65...95         // fair into poor
        case .pop:
            return 75...130        // poor, intermittent contact
        case .line:
            return 60...100        // fair into poor; mains pickup rides on high Z
        }
    }

    /// One impedance per channel, in kΩ.
    ///
    /// Healthy channels vary around `config.impedanceTypicalKOhm` rather than
    /// sitting on it, and the frontal-most electrodes are nudged upward: on a
    /// real cap the forehead sites are the ones that fight hair-free skin
    /// preparation the least but dry out the fastest, and a montage where every
    /// good channel reads identically looks synthetic on sight.
    static func values(
        config: SimulationConfig,
        montage: Montage,
        source: inout GaussianSource
    ) -> [Float] {
        (0..<config.channelCount).map { index in
            let channelNumber = index + 1
            let defect = config.badChannels[channelNumber]

            // A true electrolyte bridge is a low-resistance path even when the
            // two channels are not otherwise labelled as defective.
            let isBridged = config.bridgedChannelPairs?.contains {
                $0.firstChannel == channelNumber || $0.secondChannel == channelNumber
            } ?? false

            if let defect {
                let span = range(for: defect)
                let position = min(max(source.uniform(), 0), 1)
                return Float(span.lowerBound + position * (span.upperBound - span.lowerBound))
            }

            if isBridged {
                let span = range(for: .flat)
                let position = min(max(source.uniform(), 0), 1)
                return Float(span.lowerBound + position * (span.upperBound - span.lowerBound))
            }

            // Healthy: lognormal scatter around the requested typical value.
            //
            // The clamp is relative to that value, not to a fixed healthy band.
            // Clamping to a fixed band instead makes `--impedance 45` collapse
            // every channel onto the band's ceiling, which is both wrong and
            // silently wrong. Asking for a high typical impedance is a
            // legitimate request — it models a cap that was prepped badly — and
            // some channels landing in EVA's fair or poor bands is the correct
            // consequence of it.
            let typical = config.impedanceTypicalKOhm
            let scattered = typical * exp(0.35 * source.gaussian())
            return Float(min(max(scattered, 0.4 * typical), 2.5 * typical))
        }
    }

    /// Johnson-Nyquist voltage noise over the sampled bandwidth, in µV RMS.
    /// R is the measured contact impedance and B is Nyquist. This deliberately
    /// models only the contact's white thermal term; biological and amplifier
    /// noise remain separate components of the simulator.
    static func thermalNoiseRMSMicrovolts(
        impedanceKOhm: Double,
        samplingRate: Double,
        temperatureKelvin: Double
    ) -> Double {
        let resistanceOhms = max(0, impedanceKOhm) * 1_000
        let bandwidthHz = max(0, samplingRate) / 2
        let volts = sqrt(4 * boltzmannJoulesPerKelvin * temperatureKelvin
            * resistanceOhms * bandwidthHz)
        return volts * 1_000_000
    }

    /// Adds independent white contact noise and returns the analytic RMS used
    /// for each channel. A dedicated seed stream makes the result independent
    /// of neural source count and every other artifact family.
    static func applyThermalNoise(
        to channels: inout [[Double]],
        impedances: [Float],
        config: SimulationConfig,
        source: inout GaussianSource
    ) -> [Double] {
        guard let model = config.impedanceNoise else {
            return [Double](repeating: 0, count: channels.count)
        }
        var rms = [Double](repeating: 0, count: channels.count)
        for channel in channels.indices {
            guard channel < impedances.count else { continue }
            let amplitude = thermalNoiseRMSMicrovolts(
                impedanceKOhm: Double(impedances[channel]),
                samplingRate: config.samplingRate,
                temperatureKelvin: model.temperatureKelvin
            )
            rms[channel] = amplitude
            for sample in channels[channel].indices {
                channels[channel][sample] += amplitude * source.gaussian()
            }
        }
        return rms
    }

    /// Relative capacitive mains pickup for an electrode. The exponent is an
    /// explicit phenomenological assumption; clamping prevents a pathological
    /// contact from making the synthetic recording numerically useless.
    static func lineNoiseScale(
        impedanceKOhm: Double,
        config: SimulationConfig
    ) -> Double {
        guard let model = config.impedanceNoise else { return 1 }
        let reference = max(model.referenceImpedanceKOhm ?? 12, 1e-12)
        let raw = pow(max(impedanceKOhm, 0) / reference,
                      model.lineNoiseImpedanceExponent)
        return min(max(raw, 0.05), model.maximumLineNoiseScale)
    }

    /// Rewrites `info1.xml` inside an already-written MFF package to carry an
    /// `ICAL` calibration block.
    ///
    /// `MFFWriter` deliberately strips calibrations on export — EVA stores
    /// calibrated physical samples, so re-emitting `GCAL` would make other
    /// readers scale the data twice — and writes a minimal `info1.xml` with no
    /// calibrations at all. Impedance therefore has to be added afterwards, the
    /// same way the electrode geometry is.
    ///
    /// Adding `ICAL` is safe in a way that adding `GCAL` would not be: EVA's
    /// reader applies `GCAL` to the samples but only *parses* `ICAL`, into
    /// `impedancesKOhm`. Nothing here rescales the data.
    ///
    /// `beginTime` must be zero. The reader skips any calibration block whose
    /// begin time is non-zero, on the grounds that a later measurement does not
    /// describe the start of the recording.
    static func writeInfoXML(impedances: [Float], to packageURL: URL) throws {
        var channels = ""
        for (index, value) in impedances.enumerated() {
            channels += "        <ch n=\"\(index + 1)\">\(String(format: "%.3f", value))</ch>\n"
        }

        let xml = """
        <?xml version="1.0" encoding="UTF-8"?>
        <dataInfo>
          <generalInformation>
            <fileDataType>
              <EEG/>
            </fileDataType>
          </generalInformation>
          <calibrations>
            <calibration>
              <type>ICAL</type>
              <beginTime>0</beginTime>
              <channels>
        \(channels)      </channels>
            </calibration>
          </calibrations>
        </dataInfo>
        """
        try xml.write(
            to: packageURL.appendingPathComponent("info1.xml"),
            atomically: true,
            encoding: .utf8
        )
    }
}
