#!/usr/bin/env python3
"""Copy the root planning documents into the MkDocs tree before a site build.

`ROADMAP.md`, `ROADMAP_COMPLETE.md` and `docs/design/` are authored at the
repository root so GitHub renders them and so code comments can cite stable
paths. MkDocs can only see files under `docs_dir` (`docs/manual`), so this
script mirrors them into `docs/manual/development/` and rewrites the
cross-document links to match the site layout.

The copies are generated artifacts and are git-ignored: the root files are the
only source of truth, so there is nothing to keep in sync by hand.

    python3 scripts/sync-planning-docs.py        # write the copies
    python3 scripts/sync-planning-docs.py --check # verify they are current

Run it before `mkdocs build` or `mkdocs serve`; CI runs it in the docs workflow.
"""

from __future__ import annotations

import argparse
import re
import shutil
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DEST = ROOT / "docs" / "manual" / "development"
DESIGN_SRC = ROOT / "docs" / "design"

GITHUB_BLOB = "https://github.com/pmolfese/EVA/blob/main/"

# Banner added to each copied page so a reader on the published site knows the
# page is generated and where to edit it.
BANNER = """!!! info "Generated page"
    This page is published from `{source}` at the repository root.
    Edit that file; this copy is regenerated by
    `scripts/sync-planning-docs.py` on every documentation build.

"""


def demote_headings(text: str) -> str:
    """Push every heading below the document title down one level.

    The roadmap files use `# N. Section` for their twelve subsystems, which is
    right for GitHub but collides with MkDocs' one-h1-per-page convention:
    Material builds the in-page table of contents from the first h1's subtree
    only, so every section and milestone would be missing from it. Demoting
    makes the sections the TOC's top level.

    Anchors are derived from heading *text*, not level, so this never moves a
    link. Fenced code is skipped so `#` comments inside it survive.
    """
    out: list[str] = []
    in_fence = False
    seen_title = False
    for line in text.split("\n"):
        if line.lstrip().startswith("```"):
            in_fence = not in_fence
            out.append(line)
            continue
        m = re.match(r"^(#{1,5})(\s+.*)$", line) if not in_fence else None
        if m:
            if not seen_title and len(m.group(1)) == 1:
                seen_title = True          # the document title keeps its level
            else:
                line = "#" + m.group(1) + m.group(2)
        out.append(line)
    return "\n".join(out)


def rewrite_roadmap(text: str) -> str:
    """Links as written at the repository root -> links inside development/."""
    text = text.replace("](docs/design/README.md)", "](design/index.md)")
    text = re.sub(r"\]\(docs/design/([^)]+)\)", r"](design/\1)", text)
    text = text.replace("](ROADMAP_COMPLETE.md)", "](roadmap-complete.md)")
    text = text.replace("](ROADMAP.md)", "](roadmap.md)")
    return demote_headings(text)


def rewrite_design(text: str) -> str:
    """Links as written inside docs/design/ -> links inside development/design/."""
    text = text.replace("](README.md)", "](index.md)")
    # Repository paths that only resolve on GitHub, not on the docs site.
    text = re.sub(
        r"\]\((EVA/[^)]*)\)",
        lambda m: f"]({GITHUB_BLOB}{m.group(1)})",
        text,
    )
    return text


def planned_files() -> dict[Path, str]:
    """Map destination path -> rendered content."""
    out: dict[Path, str] = {}

    for src_name, dest_name in [
        ("ROADMAP.md", "roadmap.md"),
        ("ROADMAP_COMPLETE.md", "roadmap-complete.md"),
    ]:
        src = ROOT / src_name
        body = rewrite_roadmap(src.read_text(encoding="utf-8"))
        out[DEST / dest_name] = BANNER.format(source=src_name) + body

    for src in sorted(DESIGN_SRC.glob("*.md")):
        dest_name = "index.md" if src.name == "README.md" else src.name
        body = rewrite_design(src.read_text(encoding="utf-8"))
        out[DEST / "design" / dest_name] = (
            BANNER.format(source=f"docs/design/{src.name}") + body
        )

    return out


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true",
                    help="exit non-zero if the copies are missing or stale")
    args = ap.parse_args()

    files = planned_files()

    if args.check:
        stale = [
            p for p, content in files.items()
            if not p.exists() or p.read_text(encoding="utf-8") != content
        ]
        extra = [
            p for p in DEST.rglob("*.md") if p not in files
        ] if DEST.exists() else []
        if stale or extra:
            for p in stale:
                print(f"stale or missing: {p.relative_to(ROOT)}", file=sys.stderr)
            for p in extra:
                print(f"orphaned: {p.relative_to(ROOT)}", file=sys.stderr)
            print("run: python3 scripts/sync-planning-docs.py", file=sys.stderr)
            return 1
        print(f"{len(files)} planning pages are current")
        return 0

    if DEST.exists():
        shutil.rmtree(DEST)
    for path, content in files.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")

    print(f"synced {len(files)} planning pages into "
          f"{DEST.relative_to(ROOT)}/")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
