//
//  PipelineRegressionTests.swift
//  EVATests
//
//  Developed by P. Molfese, National Institutes of Health (NIH).
//
//  This software is a "work of the United States Government" prepared by a federal
//  employee as part of official duties. As such, it is not subject to copyright
//  protection within the United States (17 U.S.C. § 105). International copyrights
//  may apply.
//
//  End-to-end pipeline regression against known ground truth (roadmap 7.1-7.2).
//
//  The loop: EVASimulate generates a recording whose clean signal is known, EVA
//  processes it headlessly, and the result is scored against that clean signal.
//  Nothing else in the repository notices when EVA's correction quality drifts —
//  a changed filter, a changed template rule, a reordered stage all still emit a
//  perfectly valid recording, and the only symptom is that results move.
//
//  ## Why this asserts what it asserts
//
//  Suites like this die one of two deaths. Assert an exact value and every
//  legitimate improvement breaks the build until someone mutes it. Assert a
//  loose bound and nothing is ever caught. Both failure modes end with the suite
//  being ignored, which is worse than not having it.
//
//  So there are three assertions per case, and they do different jobs:
//
//  1. **A floor.** Correction quality must not fall below a committed value.
//     This is the regression check proper.
//  2. **A ceiling.** For the locked-clock gradient case the *best possible*
//     result is known analytically, and a score above it means something is
//     wrong in a way a floor can never catch — most likely ground truth leaking
//     into the correction. See below.
//  3. **A watermark.** The achieved value is committed and compared with a
//     tolerance, so a change shows up as a reviewable diff rather than silence.
//     A floor alone hides slow drift: a number can fall from 6.2 to 4.1 over
//     years without ever tripping a floor of 4.0.
//
//  ## The analytic ceiling
//
//  Average-artifact subtraction with locked clocks cancels the artifact exactly.
//  What is left is the EEG that the template averaged in along the way, whose
//  standard deviation is `std(EEG)/sqrt(N)` over an N-volume template. So the
//  best attainable broadband SNR is about `sqrt(N)` — a "perfect" AAS over 8
//  donor volumes scores near 3, not infinity.
//
//  A method scoring materially above that is either doing something smarter than
//  averaging, or it is cheating — and on a simulated recording, where the clean
//  signal is sitting in the next directory, cheating is a real possibility that
//  an end-to-end harness would otherwise conceal.
//
//  ## Running
//
//  The corpus is generated by `run-all-tests.sh` into `.regression-corpus/` at
//  the repository root. When it is absent these tests **skip** rather than fail,
//  so a bare `xcodebuild test` stays fast and green for someone working on
//  unrelated code.
//
//  To re-record the watermark after an intended change, set
//  `EVA_UPDATE_WATERMARK=1`; the test then prints the value to paste in and
//  fails deliberately, so re-recording is always an explicit edit.
//

import Testing
import Foundation
@testable import EVA

struct PipelineRegressionTests {

    // MARK: - Corpus and watermark location

    /// `<repo>/.regression-corpus`, resolved from this file rather than the
    /// working directory, which xcodebuild does not set predictably.
    static let corpusDirectory: URL = {
        URL(fileURLWithPath: #filePath)     // <repo>/EVATests/Pipeline/ThisFile.swift
            .deletingLastPathComponent()     // <repo>/EVATests/Pipeline
            .deletingLastPathComponent()     // <repo>/EVATests
            .deletingLastPathComponent()     // <repo>
            .appendingPathComponent(".regression-corpus")
    }()

    static let watermarkURL: URL = Fixtures.directory
        .appendingPathComponent("pipeline-watermark.json")

    struct Watermark: Codable {
        var broadbandSNR: Double
        var note: String?
    }

    static func watermark(for caseName: String) -> Watermark? {
        guard let data = try? Data(contentsOf: watermarkURL),
              let all = try? JSONDecoder().decode([String: Watermark].self, from: data) else {
            return nil
        }
        return all[caseName]
    }

    // MARK: - Scoring

    /// Broadband SNR against the clean recording: `std(clean) / std(clean - corrected)`.
    ///
    /// The same definition `eva-simulate score` uses, reimplemented here rather
    /// than shelling out so the assertion runs in-process with the pipeline.
    static func broadbandSNR(clean: [[Float]], corrected: [[Float]], padSeconds: Int) -> Double {
        var signalSquares = 0.0
        var residualSquares = 0.0
        for channel in 0..<min(clean.count, corrected.count) {
            let count = min(clean[channel].count, corrected[channel].count)
            guard count > 2 * padSeconds else { continue }
            for sample in padSeconds..<(count - padSeconds) {
                let truth = Double(clean[channel][sample])
                signalSquares += truth * truth
                let residual = truth - Double(corrected[channel][sample])
                residualSquares += residual * residual
            }
        }
        guard residualSquares > 1e-30 else { return .infinity }
        return (signalSquares / residualSquares).squareRoot()
    }

    // MARK: - Cases

    @Test func lockedClockGradientCorrectionHoldsItsQuality() async throws {
        let caseName = "gradient-locked"
        let caseDirectory = Self.corpusDirectory.appendingPathComponent(caseName)
        let noisyURL = caseDirectory.appendingPathComponent("sim_noisy.mff")
        let cleanURL = caseDirectory.appendingPathComponent("sim_clean.mff")

        // Skip, do not fail, when the corpus has not been generated. Someone
        // editing an unrelated part of EVA should not have to run the simulator.
        guard FileManager.default.fileExists(atPath: noisyURL.path),
              FileManager.default.fileExists(atPath: cleanURL.path) else {
            print("""
                PipelineRegressionTests: no corpus at \(Self.corpusDirectory.path) — skipping. \
                Run ./run-all-tests.sh to generate it.
                """)
            return
        }

        let donorVolumes = 8
        var script = EVAProcessingScript()
        script.append(EVAProcessingStep(
            operation: .mriGradientCorrection,
            parameters: [
                "trMarkerCode": "TREV",
                "method": "MAS",
                "donorVolumes": String(donorVolumes),
                // Pin the compute path. The Metal and CPU backends agree only to
                // a tolerance, CI machines have no usable Metal device, and a
                // watermark recorded on one backend would fail forever on the
                // other. GPU/CPU agreement has its own test.
                "backend": "cpu",
                // No alignment or upsampling: this case is about template
                // subtraction with locked clocks, and interpolation would put a
                // second mechanism between the input and the score.
                "alignment": "false",
                "subSample": "false",
                "upsampleFactor": "1"
            ]
        ))

        let outputFolder = FileManager.default.temporaryDirectory
            .appendingPathComponent("eva-regression-\(UUID().uuidString)")
        defer { try? FileManager.default.removeItem(at: outputFolder) }

        let outcome = try await HeadlessBatchProcessor.process(
            url: noisyURL, script: script, outputFolder: outputFolder
        )
        guard case .completed(let correctedURL) = outcome else {
            Issue.record("gradient correction did not complete: \(outcome)")
            return
        }

        let clean = try MFFReader().loadSignal(from: cleanURL)
        let corrected = try MFFReader().loadSignal(from: correctedURL)
        try #require(clean.numberOfChannels == corrected.numberOfChannels)

        // Trim the edges: the first and last template windows have fewer donor
        // volumes available, so their residual is not representative of the
        // method and would make the score depend on recording length.
        let pad = Int(2 * clean.samplingRate)
        let achieved = Self.broadbandSNR(
            clean: clean.data, corrected: corrected.data, padSeconds: pad
        )

        // The analytic ceiling. A median template is slightly less efficient
        // than a mean at suppressing Gaussian noise — asymptotically by
        // sqrt(pi/2) — so MAS cannot beat sqrt(N) either. Keep only a 2%
        // numerical tolerance: the previous 25% allowance admitted scores from
        // 3.00 to 3.75 even though that entire range is impossible for this
        // method and therefore defeated the leakage check's purpose.
        let theoreticalCeiling = Double(donorVolumes + 1).squareRoot()
        let ceiling = theoreticalCeiling * 1.02

        if ProcessInfo.processInfo.environment["EVA_UPDATE_WATERMARK"] == "1" {
            Issue.record("""
                EVA_UPDATE_WATERMARK is set. Record this in \
                EVATests/Fixtures/pipeline-watermark.json under "\(caseName)":
                    "broadbandSNR": \(String(format: "%.4f", achieved))
                Failing deliberately so re-recording is always an explicit edit.
                """)
            return
        }

        guard let watermark = Self.watermark(for: caseName) else {
            Issue.record("""
                No watermark for "\(caseName)" in \(Self.watermarkURL.path). \
                Achieved broadband SNR \(String(format: "%.4f", achieved)); \
                add it, or re-run with EVA_UPDATE_WATERMARK=1.
                """)
            return
        }

        // Ceiling: above this, something is leaking truth into the correction.
        #expect(
            achieved <= ceiling,
            """
            broadband SNR \(String(format: "%.3f", achieved)) exceeds the analytic ceiling \
            \(String(format: "%.3f", ceiling)) for a \(donorVolumes)-donor template. \
            Template subtraction cannot do better than sqrt(N) with locked clocks (plus the \
            stated 2% numerical tolerance), so this \
            means the correction is using information it should not have.
            """
        )

        // Floor: a 15% fall is a regression. Wide enough to absorb float-level
        // differences across machines, narrow enough that a real change trips it.
        let floor = watermark.broadbandSNR * 0.85
        #expect(
            achieved >= floor,
            """
            broadband SNR fell to \(String(format: "%.3f", achieved)) from a recorded \
            \(String(format: "%.3f", watermark.broadbandSNR)); floor is \
            \(String(format: "%.3f", floor)).
            """
        )

        // Watermark: an improvement is not a failure, but it should be recorded
        // rather than left to drift silently.
        if achieved > watermark.broadbandSNR * 1.15 {
            Issue.record("""
                broadband SNR improved to \(String(format: "%.3f", achieved)) from a recorded \
                \(String(format: "%.3f", watermark.broadbandSNR)). That is good news — \
                re-record the watermark with EVA_UPDATE_WATERMARK=1 so the gain is kept.
                """)
        }
    }
}
