//
//  MNEReferenceTests.swift
//  EVATests
//
//  Developed by P. Molfese, National Institutes of Health (NIH).
//
//  This software is a "work of the United States Government" prepared by a federal
//  employee as part of official duties. As such, it is not subject to copyright
//  protection within the United States (17 U.S.C. § 105). International copyrights
//  may apply.
//
//  Cross-checks the processing steps EVA and MNE-Python both implement —
//  spherical-spline bad-channel interpolation, average referencing, epoch
//  extraction, baseline correction, and trial averaging — against reference
//  numbers computed by MNE. The fixture (`EVATests/Fixtures/Compare/mne_reference.json`)
//  is generated by `Tools/mne-compare/make_reference.py`; see that script for
//  how each reference value was produced and read its module docstring for
//  the two real convention differences these tests confirm rather than paper
//  over (epoch length, baseline-window endpoint).
//

import Foundation
import Testing
import simd
@testable import EVA

@Suite("MNE reference parity")
struct MNEReferenceTests {

    struct Reference: Decodable {
        struct Interpolation: Decodable {
            var target: String
            var good_channels: [String]
            var weights: [Double]
            var interpolated_uv: [Double]
        }
        struct AverageReference: Decodable {
            var excluded: String
            var output_uv: [[Double]]
        }
        struct Epoching: Decodable {
            var pre_stimulus: Double
            var post_stimulus: Double
            var event_samples: [Int]
            var eva_pre_samples: Int
            var eva_epoch_length: Int
            var mne_n_times: Int
            var evoked_mne_baseline_inclusive_uv: [[Double]]
            var evoked_mne_baseline_exclusive_uv: [[Double]]
            var evoked_eva_order_uv: [[Double]]
        }
        var channels: [String]
        var positions: [String: [Double]]
        var sampling_rate: Double
        var signal_uv: [[Double]]
        var interpolation: Interpolation
        var average_reference: AverageReference
        var epoching: Epoching
    }

    static let reference: Reference = {
        try! JSONDecoder().decode(Reference.self, from: Data(contentsOf: Fixtures.url("Compare/mne_reference.json")))
    }()

    private var ref: Reference { Self.reference }

    /// EVA's `ElectrodeGeometry.load` normalizes every position to a unit
    /// vector before `SphericalSpline` ever sees it (`ElectrodeGeometry.swift`
    /// line ~70); reproducing that here rather than trusting the TSV's own
    /// scale keeps this test honest about what the solver actually receives.
    private func unitPositions() -> [Int: SIMD3<Double>] {
        var out: [Int: SIMD3<Double>] = [:]
        for (index, name) in ref.channels.enumerated() {
            guard let p = ref.positions[name] else { continue }
            let v = SIMD3<Double>(p[0], p[1], p[2])
            out[index] = v / simd_length(v)
        }
        return out
    }

    private func index(of channel: String) -> Int {
        ref.channels.firstIndex(of: channel)!
    }

    private var signalAsFloat: [[Float]] {
        ref.signal_uv.map { $0.map(Float.init) }
    }

    // MARK: - Bad-channel interpolation (Perrin spherical spline)

    @Test("interpolation weights match MNE's _make_interpolation_matrix")
    func interpolationWeightsMatchMNE() throws {
        let positions = unitPositions()
        let target = index(of: ref.interpolation.target)
        let good = ref.interpolation.good_channels.map(index(of:))

        let solved = try #require(SphericalSpline.interpolationWeights(target: target, good: good, positions: positions))
        #expect(solved.indices == good, "donor order should mirror the `good` array passed in")
        #expect(solved.weights.count == ref.interpolation.weights.count)

        for (swiftWeight, mneWeight) in zip(solved.weights, ref.interpolation.weights) {
            // EVA sums 40 Legendre terms, MNE 50; the series decays like n^-7
            // (stiffness order 4), so the truncation difference is far below
            // 1e-6 and this tolerance is about floating-point solve noise,
            // not the term-count discrepancy.
            #expect(abs(swiftWeight - mneWeight) < 1e-6, "weight mismatch: \(swiftWeight) vs \(mneWeight)")
        }
        #expect(abs(solved.weights.reduce(0, +) - 1) < 1e-6, "spline weights should sum to 1")
    }

    @Test("ChannelInterpolationSolver reproduces MNE's interpolated waveform")
    func solverReproducesInterpolatedWaveform() throws {
        let signal = SyntheticSignal.make(signalAsFloat, samplingRate: ref.sampling_rate)
        let target = index(of: ref.interpolation.target)
        let positions = unitPositions()

        let result = ChannelInterpolationSolver.solve(
            target: target,
            in: signal,
            bad: [target],
            alreadyInterpolated: [],
            positions: positions
        )
        let solution = try #require(try? result.get())
        #expect(solution.replacement.count == ref.interpolation.interpolated_uv.count)
        for (swiftValue, mneValue) in zip(solution.replacement, ref.interpolation.interpolated_uv) {
            #expect(abs(Double(swiftValue) - mneValue) < 1e-3, "interpolated sample mismatch: \(swiftValue) vs \(mneValue)")
        }
    }

    // MARK: - Average reference

    @Test("average reference matches MNE's mean-subtraction, excluding the same channel")
    func averageReferenceMatchesMNE() {
        var channels = signalAsFloat
        let excluded = index(of: ref.average_reference.excluded)

        Rereferencing.applyInPlace(&channels, excluding: [excluded])

        #expect(channels.count == ref.average_reference.output_uv.count)
        for (channelIndex, expectedChannel) in ref.average_reference.output_uv.enumerated() {
            for (sampleIndex, expectedValue) in expectedChannel.enumerated() {
                let actual = Double(channels[channelIndex][sampleIndex])
                #expect(abs(actual - expectedValue) < 1e-3,
                        "ch \(channelIndex) sample \(sampleIndex): \(actual) vs \(expectedValue)")
            }
        }
    }

    // MARK: - Epoch length convention (documented difference, not a bug to fix silently)

    @Test("EVA's epoch length is one sample short of MNE's inclusive tmin/tmax convention")
    func epochLengthConventionIsDocumented() {
        let e = ref.epoching
        let expectedEvaLength = Int(((e.pre_stimulus + e.post_stimulus) * ref.sampling_rate).rounded())
        #expect(e.eva_epoch_length == expectedEvaLength, "sanity: fixture matches EpochingViewModel's own formula")
        #expect(e.mne_n_times == e.eva_epoch_length + 1,
                "MNE's Epochs(tmin,tmax) includes both endpoints (n_times = round((tmax-tmin)*sfreq)+1); EVA's preSamples+postSamples window does not include the extra trailing sample")
    }

    // MARK: - Baseline correction + trial averaging, via EVA's real PSA path

    /// Builds the same `PSABuildResult` EVA's own PSA pipeline would build for
    /// these three trials — segments computed with the exact formula
    /// `EpochingViewModel.makeBuildJob` uses (`preSamples`/`epochLength`) — then
    /// runs EVA's real `average()` and `postProcessed(baselineCorrect: true)`,
    /// unmodified production code, not a reimplementation of it.
    private func buildEvaEvoked() -> PSABuildResult {
        let e = ref.epoching
        let signal = SyntheticSignal.make(signalAsFloat, samplingRate: ref.sampling_rate)
        let segments = e.event_samples.map { eventSample -> EpochSegment in
            let start = eventSample - e.eva_pre_samples
            return EpochSegment(
                startSample: start,
                endSample: start + e.eva_epoch_length - 1,
                stimulusOffsetSamples: e.eva_pre_samples,
                category: "stim",
                sourceCode: "1",
                sourceTimeSeconds: Double(eventSample) / ref.sampling_rate,
                colorIndex: 0,
                contributingEpochCount: 1
            )
        }
        let built = PSABuildResult(signal: signal, segments: segments, message: "")
        let averaged = built.average(colorIndices: ["stim": 0])!
        return averaged.postProcessed(averageReference: false, baselineCorrect: true, badChannels: [])
    }

    @Test("EVA's average-then-baseline evoked matches MNE's baseline-then-average evoked, same window")
    func evokedMatchesMNEUnderSameBaselineWindow() {
        let result = buildEvaEvoked()
        let e = ref.epoching
        #expect(result.signal.data.count == e.evoked_eva_order_uv.count)

        for (channelIndex, expectedChannel) in e.evoked_eva_order_uv.enumerated() {
            let actualChannel = Array(result.signal.data[channelIndex].prefix(e.eva_epoch_length))
            for (sampleIndex, expectedValue) in expectedChannel.enumerated() {
                let actual = Double(actualChannel[sampleIndex])
                #expect(abs(actual - expectedValue) < 1e-3,
                        "ch \(channelIndex) sample \(sampleIndex): \(actual) vs \(expectedValue)")
            }
        }
    }

    @Test("that same evoked disagrees with MNE's default (inclusive) baseline window by a real amount")
    func evokedDivergesFromMNEsInclusiveBaselineDefault() {
        // Not a failure — a recorded fact. EVA's baseline window is
        // pre-stimulus-only (`preStart..<preEnd`, excluding the stimulus
        // sample); MNE's default `baseline=(None, 0)` includes it. Anyone
        // porting an MNE baseline window into EVA (or vice versa) needs to
        // know the boundary sample is handled differently, not assume the
        // two are interchangeable because they "both do baseline correction."
        let result = buildEvaEvoked()
        let e = ref.epoching
        var maxDiff = 0.0
        for (channelIndex, expectedChannel) in e.evoked_mne_baseline_inclusive_uv.enumerated() {
            let actualChannel = Array(result.signal.data[channelIndex].prefix(e.eva_epoch_length))
            for (sampleIndex, expectedValue) in expectedChannel.enumerated() {
                maxDiff = max(maxDiff, abs(Double(actualChannel[sampleIndex]) - expectedValue))
            }
        }
        #expect(maxDiff > 0.01, "expected a real discrepancy from the differing baseline-window endpoint, got \(maxDiff)")
    }
}
