#!/usr/bin/env python
"""Embed the idealized spherical 10-05 / 10-10 / 10-20 electrode positions
(eeg_positions, BSD-3, via MNE-Python's bundled TSVs) as Swift source.

Run with the MNE env; writes EVACore/Channels/StandardMontageData.swift.
"""
import os, mne
src = os.path.join(os.path.dirname(mne.__file__), "channels", "data", "montages")
out = os.path.join(os.path.dirname(__file__), "..", "..", "EVACore", "Channels", "StandardMontageData.swift")

def load(name):
    rows = []
    with open(os.path.join(src, name)) as f:
        header = f.readline()
        for line in f:
            label, x, y, z = line.split()
            rows.append((label, float(x), float(y), float(z)))
    return rows

full = load("spherical_1005.tsv")
subsets = {"1020": [r[0] for r in load("spherical_1020.tsv")], "1010": [r[0] for r in load("spherical_1010.tsv")]}
lines = ["//", "//  StandardMontageData.swift", "//  EVA", "//",
         "//  GENERATED by Tools/resolve-validate/export_montages.py — do not edit.",
         "//",
         "//  Idealized 10-05 electrode positions on the unit sphere (with the 10-10 and",
         "//  10-20 subsets as label lists), from the eeg_positions project",
         "//  (https://github.com/sappelhoff/eeg_positions, BSD-3-Clause, © Stefan",
         "//  Appelhoff) as redistributed by MNE-Python. Frame: +x right, +y anterior,",
         "//  +z superior; LPA/RPA/NAS on the equator. Scaled to a nominal head radius",
         "//  by `StandardMontage` at load time.", "//", "",
         "import Foundation", "",
         "nonisolated enum StandardMontageData {",
         "    /// `label x y z` per line, unit sphere.",
         "    static let spherical1005 = \"\"\""]
for label, x, y, z in full:
    lines.append(f"{label} {x:.4f} {y:.4f} {z:.4f}")
lines.append("\"\"\"")
for key, labels in subsets.items():
    lines.append(f"    static let labels{key}: [String] = [")
    for i in range(0, len(labels), 12):
        lines.append("        " + ", ".join(f'"{l}"' for l in labels[i:i+12]) + ",")
    lines.append("    ]")
lines.append("}")
with open(out, "w") as f:
    f.write("\n".join(lines) + "\n")
print("wrote", os.path.abspath(out), len(full), "positions;", {k: len(v) for k, v in subsets.items()})
